name: DemoNewCD
on:
  workflow_dispatch:
  
jobs:
  build:
       runs-on: ubuntu-latest
       steps:
        - name: Run a one-line script
          run: echo Hello, world!
          
  deploy-dev:
    runs-on: ubuntu-latest
    environment:
       name: dev
       url: 'dev.devfelipeborges.com.br'
    needs: build
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm run build
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.2.0
      with: 
       local-dir: ./build/
       server-dir: ./dev
       server: ${{ secrets.ftp_host }}
       username: ${{ secrets.ftp_user }}
       password: ${{ secrets.ftp_password }}
       run: sudo cp -R build/*/var/www
    strategy:
      matrix:
        node-version: [12.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
 
  deploy-hmg:
    runs-on: ubuntu-latest
    environment:
       name: homolog
       url: 'dev.devfelipeborges.com.br'
    needs: deploy-dev
    steps:
       - name: Run a one-line script
         run: echo Deploy homolog
         
  deploy-prod:
    runs-on: ubuntu-latest
    environment:
       name: prod
       url: 'dev.devfelipeborges.com.br'
    needs: deploy-hmg
    steps:
       - name: Run a one-line script
         run: echo Deploy PRD      
       
